### ISSUE TITLE
Prepare for 0.3 release

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/Roadmap.jl#12]
It looks like the 0.3 release candidate series may start soon. I'd like to make sure that we get everything in shape for the 0.3 release (or very soon after), so that we can feel confident that people who download the final 0.3 binary will be able to get a set of stable packages for statistics.

So please raise any issues that stats folks feel we need to finalize before the 0.3 release.

**Comment by saosebastiao** [comment]
Some things that would be nice for me:
1) A centralized documentation site with a standardized doc format. While I like R's documentation format (Description, Usage, Arguments, Details, Return Value, See Also, Examples), I would be happy if I could just know where to find the docs for the library I'm using. 
2) All of these: https://github.com/JuliaStats/Roadmap.jl/issues/3
3) Pull in the DecisionTrees library and modify to use the ModelFrame/Formula interface. 
4) Maybe it is a little too early to implement, but I like where this discussion is going: https://github.com/JuliaStats/Roadmap.jl/issues/4 . Maybe we could have a finalized standard by 0.3, so that we could work towards implementation in 0.4. 

Some other things that would be nice to work on:
1) Some good implementations of Neural Nets. I like the idea of the Theano port that S Wade was proposing in this thread: https://groups.google.com/forum/#!msg/julia-stats/oy2hYFQ9Gno/hLEZcr4cE9QJ
2) ARIMA, ETS, and Holt Winters for Time Series models. I particularly like the forecast package in R. 

Don't take these as demands though. I have heard about Julia for a while, but it wasn't until a few weeks ago that I actually discovered how awesome it is. I'm trying to absorb as much as possible so that I can actually contribute to make Julia my go-to modeling language, as opposed to asking others to do it for me:)

**Comment by ViralBShah** [comment]
Close this?
